### ISSUE TITLE
Ability to skip rows

### ISSUE THREAD

**Issue by mattisdada** [Claviz/bellboy#15]
It would be fantastic being able to pass `null` / `undefined` to yield in `recordGenerator` to be able to skip a row

**Comment by jansivans** [comment]
Hi.
This isn't done intentionally because in some scenarios missing (`null`/`undefined`) information needs to be presented. 
But there is a solution for you.
You can use `batchTransformer` function in destination to filter out unneccessary data.
Here is an example:
Imagine you are having an array of `a` and `b` characters as a source and you need to skip `b` -
```js
const bellboy = require('bellboy');

(async () => {
    const sourceData = ['a', 'b', 'a', 'a', 'b', 'b', 'b', 'a'];
    const processor = new bellboy.DynamicProcessor({
        generator: async function* () {
            for (const item of sourceData) {
                // We don't need `b`, so we generate an `undefined`.
                yield item === 'b' ? undefined : item;
            }
        }
    });
    const destination = new bellboy.StdoutDestination({
        batchTransformer: async (rows) => {
            // Skip undefined items
            return rows.filter(x => x !== undefined);
        }
    });
    const job = new bellboy.Job(processor, [destination]);
    await job.run();
})();
```
Please let me know if I have answered your question.

**Comment by mattisdada** [comment]
This still leaves a problem with empty destinations failing (for example, the inbuilt MSSQL destination) instead of skipping

**Comment by jansivans** [comment]
What you mean by empty destination and why is it failing?
Can you provide an example?

**Comment by mattisdada** [comment]
If the MS SQL destination has an empty array as an input it crashes because the transaction is expecting at least one record

**Comment by AlexTimo** [comment]
Hi @mattisdada,

Could post a snippet of your script? It would help us to reproduce the issue.

**Comment by AlexTimo** [comment]
Closing the issue due to inactivity.
